/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlythuvien;

/**
 *
 * @author ADMIN
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        init();
        setLocationRelativeTo(null);
    }

    void init() {
        setTitle("CHÀO MỪNG ĐẾN VỚI THƯ VIỆN");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnquanlisach = new javax.swing.JButton();
        btnquanliphieumuon = new javax.swing.JButton();
        btnquanlithuthu = new javax.swing.JButton();
        btnquanlithongke = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnquanliloaisach = new javax.swing.JButton();
        btnnhacungcap = new javax.swing.JButton();
        btnphieucungcap = new javax.swing.JButton();
        btndangxuat = new javax.swing.JButton();
        anhnen = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnquanlisach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnquanlisach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Lists.png"))); // NOI18N
        btnquanlisach.setText("QUẢN LÍ SÁCH");
        btnquanlisach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquanlisachActionPerformed(evt);
            }
        });
        getContentPane().add(btnquanlisach, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 190, 70));

        btnquanliphieumuon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnquanliphieumuon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/List.png"))); // NOI18N
        btnquanliphieumuon.setText("QUẢN LÍ PHIẾU MƯỢN");
        btnquanliphieumuon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquanliphieumuonActionPerformed(evt);
            }
        });
        getContentPane().add(btnquanliphieumuon, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 210, 70));

        btnquanlithuthu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnquanlithuthu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Clien list.png"))); // NOI18N
        btnquanlithuthu.setText("QUẢN LÍ THỦ THƯ");
        btnquanlithuthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquanlithuthuActionPerformed(evt);
            }
        });
        getContentPane().add(btnquanlithuthu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 190, 70));

        btnquanlithongke.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnquanlithongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Notes.png"))); // NOI18N
        btnquanlithongke.setText("QUẢN LÍ THỐNG KÊ");
        btnquanlithongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquanlithongkeActionPerformed(evt);
            }
        });
        getContentPane().add(btnquanlithongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 230, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/fpt.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, -1, -1));

        btnquanliloaisach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnquanliloaisach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Notes.png"))); // NOI18N
        btnquanliloaisach.setText("QUẢN LÍ LOẠI SÁCH");
        btnquanliloaisach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquanliloaisachActionPerformed(evt);
            }
        });
        getContentPane().add(btnquanliloaisach, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 210, 70));

        btnnhacungcap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Company.png"))); // NOI18N
        btnnhacungcap.setText("Nhà cung cấp ");
        btnnhacungcap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhacungcapActionPerformed(evt);
            }
        });
        getContentPane().add(btnnhacungcap, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 210, 70));

        btnphieucungcap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Document.png"))); // NOI18N
        btnphieucungcap.setText("Phiếu cung cấp");
        btnphieucungcap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnphieucungcapActionPerformed(evt);
            }
        });
        getContentPane().add(btnphieucungcap, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 230, 70));

        btndangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete.png"))); // NOI18N
        btndangxuat.setText("Đăng xuất");
        btndangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangxuatActionPerformed(evt);
            }
        });
        getContentPane().add(btndangxuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 210, 70));

        anhnen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        anhnen.setForeground(new java.awt.Color(204, 204, 204));
        anhnen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/library-488690_1920.jpg"))); // NOI18N
        getContentPane().add(anhnen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 320));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnquanlithuthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquanlithuthuActionPerformed
        QLThuThu qltt = new QLThuThu();
        qltt.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnquanlithuthuActionPerformed

    private void btnquanliphieumuonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquanliphieumuonActionPerformed
        QLPhieuMuon qlpm = new QLPhieuMuon();
        qlpm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnquanliphieumuonActionPerformed

    private void btnquanlithongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquanlithongkeActionPerformed
        QLThongKe qltk = new QLThongKe();
        qltk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnquanlithongkeActionPerformed

    private void btnquanliloaisachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquanliloaisachActionPerformed
        QLSach qls = new QLSach();
        qls.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnquanliloaisachActionPerformed

    private void btnphieucungcapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnphieucungcapActionPerformed
        PhieuCungCapSach pccs = new PhieuCungCapSach();
        pccs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnphieucungcapActionPerformed

    private void btndangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangxuatActionPerformed
        DangNhap dn = new DangNhap();
        dn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btndangxuatActionPerformed

    private void btnnhacungcapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhacungcapActionPerformed
        NhaCungCap ncc = new NhaCungCap();
        ncc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnnhacungcapActionPerformed

    private void btnquanlisachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquanlisachActionPerformed
        QLSach qls = new QLSach();
        qls.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnquanlisachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhnen;
    private javax.swing.JButton btndangxuat;
    private javax.swing.JButton btnnhacungcap;
    private javax.swing.JButton btnphieucungcap;
    private javax.swing.JButton btnquanliloaisach;
    private javax.swing.JButton btnquanliphieumuon;
    private javax.swing.JButton btnquanlisach;
    private javax.swing.JButton btnquanlithongke;
    private javax.swing.JButton btnquanlithuthu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
