/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlythuvien;

import dao.LoaiSachDAO;
import dao.QLySachDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Sach;

/**
 *
 * @author Siu
 */
public class QLSach extends javax.swing.JFrame {

    dao.QLySachDAO qLySachDAO = new QLySachDAO();
    DefaultTableModel tblmoModel;
    ArrayList<model.Sach> list = new ArrayList<>();
    dao.LoaiSachDAO loaiSachDAO = new LoaiSachDAO();
    ArrayList<model.LoaiSach> listls = new ArrayList<>();

    public QLSach() {
        initComponents();
        list = qLySachDAO.getlist();
        initTable();
        comboboxTrangThai();
        maloai();
        filltotable();
        setLocationRelativeTo(null);
    }

    void initTable() {
        setTitle("CHÀO MỪNG ĐẾN VỚI THƯ VIỆN");
        tblmoModel = (DefaultTableModel) tblSach.getModel();
        tblmoModel.setColumnIdentifiers(new String[]{"Mã sách", "Tên sách", "Giá Thuê", "Số lượng", "Trạng thái", "Mô tả ", "Tác giả", "NXB", "Mã loại"});
    }

    public void comboboxTrangThai() {
        cboTrangThai.addItem("Hết sách");
        cboTrangThai.addItem("Còn sách");
        System.out.println("Item in combobox" + cboTrangThai.getItemCount());
    }

    private void maloai() {
        try {
            listls = loaiSachDAO.getList();
            cbomaloai.removeAllItems();
            for (model.LoaiSach ls : listls) {
                cbomaloai.addItem(ls.getTenLoai());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void ShowDetail(int Index) {
        try {
            txtMaSach.setText(tblSach.getValueAt(Index, 0) + "");
            txtTenSach.setText(tblSach.getValueAt(Index, 1) + "");
            txtGiaThue.setText(tblSach.getValueAt(Index, 2) + "");
            txtSoLuong.setText(tblSach.getValueAt(Index, 3) + "");
            Object objTrangThai = tblSach.getValueAt(Index, 4);
            if (objTrangThai instanceof Integer) {
                int trangthai = (int) objTrangThai;
                if (trangthai == 0) {
                    cboTrangThai.setSelectedItem("Hết sách");
                } else {
                    cboTrangThai.setSelectedItem("Còn sách");
                }
            } else if (objTrangThai instanceof String) {
                String trangthai = (String) objTrangThai;
                cboTrangThai.setSelectedItem(trangthai);
            }
            txtMoTa.setText(tblSach.getValueAt(Index, 5) + "");
            txtTacGia.setText(tblSach.getValueAt(Index, 6) + "");
            txtngayxb.setText(tblSach.getValueAt(Index, 7) + "");
            Object objmaloai = tblSach.getValueAt(Index, 8);
            cbomaloai.setSelectedItem(objmaloai);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void filltotable() {
        tblmoModel.setRowCount(0);
        String trangThai = "";
        for (model.Sach qls : list) {
            if (qls.getTrangthai() == 0) {
                trangThai = "Hết sách";
            } else {
                trangThai = "Còn sách";
            }
            String tenloai = "";
            for (int i = 0; i < listls.size(); i++) {
                if (listls.get(i).getMaLoai().equalsIgnoreCase(qls.getMaloai() + "")) {
                    tenloai = listls.get(i).getTenLoai();
                }
            }
            Object[] row = new Object[]{qls.getMasach(), qls.getTensach(), qls.getGiathue(), qls.getSoluong(), trangThai, qls.getMota(), qls.getTentacgia(), qls.getNgay(), tenloai};
            tblmoModel.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ttt = new javax.swing.JPanel();
        lbTacgia = new javax.swing.JLabel();
        txtTenSach = new javax.swing.JTextField();
        txtGiaThue = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        lbMasach = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JTextField();
        txtMoTa = new javax.swing.JTextField();
        txtTacGia = new javax.swing.JTextField();
        txtngayxb = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        lbTensach = new javax.swing.JLabel();
        btnMoi = new javax.swing.JButton();
        lbSotrang = new javax.swing.JLabel();
        lbNgonngu = new javax.swing.JLabel();
        lbGiatri = new javax.swing.JLabel();
        lbSoluong = new javax.swing.JLabel();
        txtTimkiem = new javax.swing.JTextField();
        lbNamxuatban = new javax.swing.JLabel();
        cboTrangThai = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnTimkiem = new javax.swing.JButton();
        cbomaloai = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTacgia.setText("Tác giả :");

        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        lbMasach.setText("Mã sách :");

        txtTacGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTacGiaActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm sách");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa sách");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        lbTensach.setText("Tên sách:");

        btnMoi.setText("Làm mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        lbSotrang.setText("Giá thuê :");

        lbNgonngu.setText("Số lượng :");

        lbGiatri.setText("Trạng thái :");

        lbSoluong.setText("Mô tả");

        txtTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimkiemActionPerformed(evt);
            }
        });

        lbNamxuatban.setText("Ngày xuất bản :");

        jLabel1.setText("Mã loại");

        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Brick house.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tttLayout = new javax.swing.GroupLayout(ttt);
        ttt.setLayout(tttLayout);
        tttLayout.setHorizontalGroup(
            tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tttLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tttLayout.createSequentialGroup()
                        .addComponent(lbMasach)
                        .addGap(34, 34, 34)
                        .addGroup(tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tttLayout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tttLayout.createSequentialGroup()
                                .addGap(465, 465, 465)
                                .addComponent(txtTimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTimkiem))))
                    .addGroup(tttLayout.createSequentialGroup()
                        .addGroup(tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSoluong)
                            .addComponent(lbNgonngu)
                            .addComponent(lbSotrang)
                            .addComponent(lbTensach))
                        .addGap(38, 38, 38)
                        .addGroup(tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tttLayout.createSequentialGroup()
                                .addGroup(tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaThue, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbNamxuatban)
                                    .addComponent(lbTacgia)
                                    .addComponent(lbGiatri))
                                .addGap(18, 18, 18)
                                .addGroup(tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtngayxb)
                                    .addComponent(txtTacGia)
                                    .addComponent(cboTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbomaloai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(tttLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)))))
                .addContainerGap())
        );
        tttLayout.setVerticalGroup(
            tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tttLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimkiem)
                    .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMasach))
                .addGap(18, 18, 18)
                .addGroup(tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTacgia)
                    .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTensach))
                .addGap(18, 18, 18)
                .addGroup(tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtngayxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNamxuatban)
                    .addComponent(txtGiaThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSotrang))
                .addGroup(tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tttLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbomaloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNgonngu))
                        .addGap(18, 18, 18)
                        .addGroup(tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbGiatri)
                            .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tttLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(lbSoluong)))
                .addGap(18, 18, 18)
                .addGroup(tttLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnCapNhat)
                    .addComponent(btnMoi)
                    .addComponent(btnXoa))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSach);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ttt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ttt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lí sách", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimkiemActionPerformed

    }//GEN-LAST:event_txtTimkiemActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        txtMaSach.setText("");
        txtTenSach.setText("");
        txtGiaThue.setText("");
        txtSoLuong.setText("");
        cboTrangThai.setSelectedIndex(-1);
        txtTacGia.setText("");
        txtMoTa.setText("");
        txtngayxb.setText("");
        cbomaloai.setSelectedIndex(0);
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        int selectedIndex = tblSach.getSelectedRow();
        if (selectedIndex != -1) {
            Sach qls = list.get(selectedIndex);
            String maloai = listls.get(cbomaloai.getSelectedIndex()).getMaLoai();
            int maLoai = Integer.parseInt(maloai);
            System.out.println(maloai);
            String maSach = txtMaSach.getText();
            String tenSach = txtTenSach.getText();
            int giaThue = Integer.parseInt(txtGiaThue.getText());
            int soLuong = Integer.parseInt(txtSoLuong.getText());
            int trangThai = cboTrangThai.getSelectedIndex();
            String tacGia = txtTacGia.getText();
            String moTa = txtMoTa.getText();
            String ngay = txtngayxb.getText();
//            int maLoai = Integer.parseInt(txtMaLoai.getText());
            qls.setMasach(maSach);
            qls.setTensach(tenSach);
            qls.setGiathue(giaThue);
            qls.setSoluong(soLuong);
            qls.setTrangthai(trangThai);
            qls.setMota(moTa);
            qls.setTentacgia(tacGia);
            qls.setNgay(ngay);
//            qls.setMaloai(maSach);
            qLySachDAO.edit(maSach, tenSach, giaThue, soLuong, trangThai, tacGia, moTa, ngay, maLoai);
            filltotable();

            JOptionPane.showMessageDialog(this, "Cập nhật thông tin khách hàng thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một khách hàng để sửa!");
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int selectedRow = tblSach.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một chuyên đề để xóa.");
            return;
        }
        String selectedMaSach = tblmoModel.getValueAt(selectedRow, 0).toString();
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn xóa chuyên đề này không?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            boolean result = qLySachDAO.hide(selectedMaSach);
            if (result) {
                JOptionPane.showMessageDialog(this, "Đã xóa thành công!");
                filltotable();
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi! Không thể xóa.");
            }
        }
        list = qLySachDAO.getlist();
        filltotable();
        txtMaSach.setText("");
        txtTenSach.setText("");
        txtGiaThue.setText("");
        txtSoLuong.setText("");
        cboTrangThai.setSelectedIndex(-1);
        txtMoTa.setText("");
        txtngayxb.setText("");
        cbomaloai.setSelectedIndex(0);

    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        model.Sach qls = new model.Sach();
        qls.setMasach(txtMaSach.getText());
        qls.setTensach(txtTenSach.getText());
        qls.setGiathue(Integer.parseInt(txtGiaThue.getText()));
        qls.setSoluong(Integer.parseInt(txtSoLuong.getText()));
//        qls.setTrangthai(Integer.parseInt((String) cboTrangThai.getSelectedItem()));
        String trangthai = cboTrangThai.getSelectedItem() + "";
        if (trangthai.equals("Còn sách")) {
            qls.setTrangthai(1);
        } else {
            qls.setTrangthai(0);
        }
        qls.setMota(txtMoTa.getText());
        qls.setTentacgia(txtTacGia.getText());
        qls.setNgay(txtngayxb.getText());
//        qls.setMaloai(Integer.parseInt(txtMaLoai.getText()));
        String maSach = txtMaSach.getText();
        String tenSach = txtTenSach.getText();
        int giaThue = Integer.parseInt(txtGiaThue.getText());
        int soLuong = Integer.parseInt(txtSoLuong.getText());
//        int trangThai = (int) cboTrangThai.getSelectedItem();
        String moTa = txtMoTa.getText();
        String tenTacGia = txtTacGia.getText();
        String ngay = txtngayxb.getText();
        String maloai = listls.get(cbomaloai.getSelectedIndex()).getMaLoai();
        int maLoai = Integer.parseInt(maloai);
        boolean result = qLySachDAO.add(qls);
        if (result) {
            JOptionPane.showMessageDialog(this, "Saved !");
        } else {
            JOptionPane.showMessageDialog(this, "Error!");
        }
        list = qLySachDAO.getlist();
        filltotable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtTacGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTacGiaActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void tblSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSachMouseClicked
        int selectedrow = tblSach.getSelectedRow();
        ShowDetail(selectedrow);
    }//GEN-LAST:event_tblSachMouseClicked

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        String maSach = txtTimkiem.getText().trim();

        if (maSach.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã sách cần tìm!");
            return;
        }
        try {
            Sach sach = qLySachDAO.search(maSach);
            if (sach != null) {
                list.clear();
                list.add(sach);
                filltotable();
            } else {
                JOptionPane.showMessageDialog(this, "Không tìm thấy sách có mã " + maSach);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu mn = new Menu();
        mn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JComboBox<String> cbomaloai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbGiatri;
    private javax.swing.JLabel lbMasach;
    private javax.swing.JLabel lbNamxuatban;
    private javax.swing.JLabel lbNgonngu;
    private javax.swing.JLabel lbSoluong;
    private javax.swing.JLabel lbSotrang;
    private javax.swing.JLabel lbTacgia;
    private javax.swing.JLabel lbTensach;
    private javax.swing.JTable tblSach;
    private javax.swing.JPanel ttt;
    private javax.swing.JTextField txtGiaThue;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTacGia;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTimkiem;
    private javax.swing.JTextField txtngayxb;
    // End of variables declaration//GEN-END:variables
}
